name: ci
on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            platform: windows
            configurePreset: Windows-Release
            build-artifact: aoc.exe

          - os: ubuntu-latest
            platform: linux
            configurePreset: Linux-Release
            build-artifact: aoc
      
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSVC
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Build with CMake
        uses: lukka/run-cmake@v10
        env:
          VCPKG_ROOT:
        with:
          configurePreset: ${{ matrix.configurePreset }}
          buildPreset: ${{ matrix.configurePreset }}

      - name: Run tests
        run: ctest --test-dir build/${{ matrix.configurePreset }} --verbose
        shell: bash
      
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: aoc-${{ matrix.platform }}
          path: build/${{ matrix.configurePreset }}/${{ matrix.build-artifact }}
